import type { DashboardOverview } from './dashboard.types';

export const dashboardMockData: DashboardOverview = {
  kpis: [
    {
      id: 'k1',
      title: 'Tổng dự án',
      value: 23,
      changeText: '+2 dự án mới',
      changeType: 'increase',
      icon: 'Building2',
    },
    {
      id: 'k2',
      title: 'Lead mới',
      value: '1.289',
      changeText: '+18,6% so với kỳ trước',
      changeType: 'increase',
      icon: 'Users',
    },
    {
      id: 'k3',
      title: 'Lịch hẹn hôm nay',
      value: 36,
      changeText: '+6 hẹn mới',
      changeType: 'increase',
      icon: 'CalendarDays',
    },
    {
      id: 'k4',
      title: 'Tỉ lệ chuyển đổi',
      value: '7,62%',
      changeText: '+1,25% so với kỳ trước',
      changeType: 'increase',
      icon: 'TrendingUp',
    },
    {
      id: 'k5',
      title: 'Bài viết đang hoạt động',
      value: 128,
      changeText: '12 bài viết mới',
      changeType: 'increase',
      icon: 'Newspaper',
    },
    {
      id: 'k6',
      title: 'Yêu cầu tư vấn',
      value: 98,
      changeText: '+5 so với hôm qua',
      changeType: 'increase',
      icon: 'PhoneCall',
    },
  ],

  leadPerformance: [
    { date: '01/05', leadNew: 520, appointments: 120, convertedCustomers: 58 },
    { date: '03/05', leadNew: 610, appointments: 145, convertedCustomers: 72 },
    { date: '05/05', leadNew: 580, appointments: 130, convertedCustomers: 65 },
    { date: '07/05', leadNew: 720, appointments: 180, convertedCustomers: 88 },
    { date: '09/05', leadNew: 690, appointments: 165, convertedCustomers: 82 },
    { date: '11/05', leadNew: 810, appointments: 210, convertedCustomers: 105 },
    { date: '13/05', leadNew: 760, appointments: 195, convertedCustomers: 98 },
    { date: '15/05', leadNew: 880, appointments: 230, convertedCustomers: 115 },
    { date: '17/05', leadNew: 920, appointments: 250, convertedCustomers: 128 },
    { date: '19/05', leadNew: 850, appointments: 220, convertedCustomers: 110 },
    { date: '21/05', leadNew: 980, appointments: 280, convertedCustomers: 142 },
    { date: '23/05', leadNew: 1050, appointments: 310, convertedCustomers: 158 },
    { date: '25/05', leadNew: 1120, appointments: 340, convertedCustomers: 170 },
    { date: '27/05', leadNew: 1180, appointments: 360, convertedCustomers: 185 },
    { date: '31/05', leadNew: 1280, appointments: 390, convertedCustomers: 198 },
  ],

  seoPerformance: [
    { date: '01/05', views: 3200, clicks: 220 },
    { date: '03/05', views: 3450, clicks: 245 },
    { date: '05/05', views: 3380, clicks: 235 },
    { date: '07/05', views: 3720, clicks: 270 },
    { date: '09/05', views: 3900, clicks: 290 },
    { date: '11/05', views: 4100, clicks: 315 },
    { date: '13/05', views: 4050, clicks: 305 },
    { date: '15/05', views: 4350, clicks: 340 },
    { date: '17/05', views: 4580, clicks: 360 },
    { date: '19/05', views: 4420, clicks: 345 },
    { date: '21/05', views: 4800, clicks: 385 },
    { date: '23/05', views: 5100, clicks: 410 },
    { date: '25/05', views: 5350, clicks: 435 },
    { date: '27/05', views: 5600, clicks: 465 },
    { date: '31/05', views: 5900, clicks: 495 },
  ],

  leadSources: [
    { name: 'Website', value: 548, percent: 42.5, color: '#2563EB' },
    { name: 'Quảng cáo', value: 362, percent: 28.1, color: '#C89B3C' },
    { name: 'Mạng xã hội', value: 202, percent: 15.7, color: '#0F9F6E' },
    { name: 'Sự kiện', value: 98, percent: 7.6, color: '#F59E0B' },
    { name: 'Giới thiệu', value: 79, percent: 6.1, color: '#7C3AED' },
  ],

  approvalTasks: [
    {
      id: 't1',
      title: 'Phê duyệt bài viết: Vinhomes Ocean Park 3 - The Crown',
      type: 'Bài viết',
      time: '25 phút trước',
      status: 'pending',
    },
    {
      id: 't2',
      title: 'Kiểm duyệt form đăng ký sự kiện',
      type: 'Form',
      time: '45 phút trước',
      status: 'processing',
    },
    {
      id: 't3',
      title: 'Cập nhật chính sách bán hàng - Vinhomes Smart City',
      type: 'Chính sách',
      time: '1 giờ trước',
      status: 'pending',
    },
    {
      id: 't4',
      title: 'Phê duyệt banner chiến dịch tháng 6',
      type: 'Banner',
      time: '2 giờ trước',
      status: 'approved',
    },
    {
      id: 't5',
      title: 'Xác nhận lịch hẹn tham quan - 0983 456 789',
      type: 'Lịch hẹn',
      time: '3 giờ trước',
      status: 'pending',
    },
  ],

  recentLeads: [
    {
      id: 'l1',
      name: 'Nguyễn Minh Anh',
      phone: '0983 456 789',
      source: 'Website',
      time: '10:24',
      status: 'new',
    },
    {
      id: 'l2',
      name: 'Trần Quốc Bảo',
      phone: '0912 345 678',
      source: 'Quảng cáo',
      time: '10:15',
      status: 'new',
    },
    {
      id: 'l3',
      name: 'Lê Thị Thu Hà',
      phone: '0934 567 890',
      source: 'Facebook',
      time: '10:05',
      status: 'new',
    },
    {
      id: 'l4',
      name: 'Phạm Hoàng Nam',
      phone: '0901 234 567',
      source: 'Website',
      time: '09:58',
      status: 'contacted',
    },
    {
      id: 'l5',
      name: 'Vũ Thị Hồng',
      phone: '0978 901 234',
      source: 'Sự kiện',
      time: '09:45',
      status: 'new',
    },
  ],

  managedProjects: [
    {
      id: 'p1',
      name: 'Vinhomes Ocean Park 3',
      thumbnail: '/images/projects/ocean-park-thumb.jpg',
      totalProducts: 5432,
      soldProducts: 3876,
      absorptionRate: 71.3,
      status: 'open',
    },
    {
      id: 'p2',
      name: 'Vinhomes Grand Park',
      thumbnail: '/images/projects/grand-park-thumb.jpg',
      totalProducts: 4168,
      soldProducts: 3102,
      absorptionRate: 74.4,
      status: 'open',
    },
    {
      id: 'p3',
      name: 'Vinhomes Smart City',
      thumbnail: '/images/projects/smart-city-thumb.jpg',
      totalProducts: 3912,
      soldProducts: 2689,
      absorptionRate: 68.7,
      status: 'open',
    },
    {
      id: 'p4',
      name: 'Vinhomes Ocean Park 2',
      thumbnail: '/images/projects/ocean-park-2-thumb.jpg',
      totalProducts: 2998,
      soldProducts: 2123,
      absorptionRate: 70.8,
      status: 'open',
    },
    {
      id: 'p5',
      name: 'Vinhomes Royal Island',
      thumbnail: '/images/projects/royal-island-thumb.jpg',
      totalProducts: 2450,
      soldProducts: 1205,
      absorptionRate: 49.2,
      status: 'upcoming',
    },
  ],

  activities: [
    {
      id: 'a1',
      title: 'Lead mới: Nguyễn Minh Anh từ Website',
      time: '10:24',
      type: 'lead',
    },
    {
      id: 'a2',
      title: 'Lịch hẹn tham quan đã được đặt',
      description: 'Ocean Park 3 - 11/05/2025 09:00',
      time: '10:18',
      type: 'appointment',
    },
    {
      id: 'a3',
      title: 'Bài viết "Top 5 lý do nên sống tại Vinhomes" đã được xuất bản',
      time: '09:50',
      type: 'post',
    },
    {
      id: 'a4',
      title: 'Form đăng ký "Sự kiện mở bán Ocean Park 3" có 12 lượt đăng ký mới',
      time: '09:35',
      type: 'form',
    },
    {
      id: 'a5',
      title: 'User Trần Thị Mai đăng nhập hệ thống',
      time: '09:15',
      type: 'user',
    },
  ],

  seoKeywords: [
    { keyword: 'vinhomes ocean park 3', position: 3, searchVolume: 14800, change: 1 },
    { keyword: 'vinhomes smart city', position: 4, searchVolume: 9900, change: 1 },
    { keyword: 'vinhomes grand park', position: 5, searchVolume: 8100, change: 0 },
    { keyword: 'mua nhà vinhomes', position: 6, searchVolume: 6600, change: -1 },
    { keyword: 'dự án vinhomes', position: 7, searchVolume: 5400, change: 1 },
  ],

  popularPosts: [
    { title: 'Vinhomes Ocean Park 3 - The Crown', views: '12.5K' },
    { title: 'Top 5 lý do nên sống tại Vinhomes', views: '8.9K' },
    { title: 'Chính sách bán hàng T5/2025', views: '7.2K' },
    { title: 'Vinhomes Smart City - Tiện ích vượt trội', views: '6.1K' },
    { title: 'Cập nhật tiến độ Vinhomes Grand Park', views: '5.8K' },
  ],

  optimizationPages: [
    { path: '/vinhomes-ocean-park-3', score: 92 },
    { path: '/vinhomes-royal-island', score: 78 },
    { path: '/chinh-sach-ban-hang', score: 65 },
    { path: '/tin-tuc', score: 84 },
  ],

  scheduledPosts: [
    { date: '15/05', time: '09:00', title: 'Vinhomes Royal Island - Sắp ra mắt' },
    { date: '16/05', time: '14:00', title: 'Livestream tư vấn dự án Ocean Park 3' },
    { date: '17/05', time: '10:00', title: 'Chính sách bán hàng T6/2025' },
    { date: '18/05', time: '09:00', title: 'Cập nhật tiến độ dự án Smart City' },
  ],

  businessMetrics: [
    {
      id: 'bm1',
      title: 'Doanh thu ước tính',
      value: '286,5 tỷ',
      changeText: '+21,4% so với kỳ trước',
      changeType: 'increase',
    },
    {
      id: 'bm2',
      title: 'Giá trị bookings',
      value: '412,3 tỷ',
      changeText: '+18,9% so với kỳ trước',
      changeType: 'increase',
    },
    {
      id: 'bm3',
      title: 'Sản phẩm đã bán',
      value: '1.248',
      changeText: '+15,2% so với kỳ trước',
      changeType: 'increase',
    },
    {
      id: 'bm4',
      title: 'Tỉ lệ hấp thụ',
      value: '68,3%',
      changeText: '+6,7% so với kỳ trước',
      changeType: 'increase',
    },
  ],

  revenueChart: [
    { date: '01/05', revenue: 22 },
    { date: '03/05', revenue: 28 },
    { date: '05/05', revenue: 35 },
    { date: '07/05', revenue: 42 },
    { date: '09/05', revenue: 38 },
    { date: '11/05', revenue: 55 },
    { date: '13/05', revenue: 48 },
    { date: '15/05', revenue: 62 },
    { date: '17/05', revenue: 70 },
    { date: '19/05', revenue: 65 },
    { date: '21/05', revenue: 78 },
    { date: '23/05', revenue: 85 },
    { date: '25/05', revenue: 82 },
    { date: '27/05', revenue: 92 },
    { date: '31/05', revenue: 98 },
  ],

  projectStatus: [
    { name: 'Đang mở bán', value: 12, percent: 52.2, color: '#0F9F6E' },
    { name: 'Sắp mở bán', value: 4, percent: 17.4, color: '#F59E0B' },
    { name: 'Đã bàn giao', value: 3, percent: 13.0, color: '#061B3A' },
    { name: 'Chuẩn bị triển khai', value: 4, percent: 17.4, color: '#7C3AED' },
  ],

  productSales: [
    { name: 'Căn hộ', value: 808, percent: 64.8, color: '#2563EB' },
    { name: 'Biệt thự', value: 195, percent: 15.7, color: '#C89B3C' },
    { name: 'Shophouse', value: 165, percent: 13.3, color: '#0F9F6E' },
    { name: 'Liền kề', value: 80, percent: 6.2, color: '#F59E0B' },
  ],
};
