import type { UserDashboardOverview } from "./user-dashboard.types";

export const userDashboardMockData: UserDashboardOverview = {
  profile: {
    id: "user_01",
    fullName: "Nguyễn Minh An",
    avatar: "/images/user/avatar-minh-an.jpg",
    memberLevel: "Kim cương",
    memberPoints: 8250,
    memberBenefitsCount: 3,
    roleLabel: "Khách hàng thân thiết",
  },
  kpis: [
    {
      id: "kpi_saved",
      title: "Dự án đã lưu",
      value: 3,
      description: "Dự án bạn quan tâm",
      icon: "Heart",
      href: "/user/du-an-quan-tam",
    },
    {
      id: "kpi_appts",
      title: "Lịch hẹn sắp tới",
      value: 2,
      description: "Trong 7 ngày tới",
      icon: "CalendarDays",
      href: "/user/lich-hen-tham-quan",
    },
    {
      id: "kpi_reqs",
      title: "Yêu cầu đang xử lý",
      value: 2,
      description: "Đang được tư vấn",
      icon: "Headphones",
      href: "/user/yeu-cau-tu-van",
    },
    {
      id: "kpi_docs",
      title: "Tài liệu mới",
      value: 4,
      description: "Cập nhật gần đây",
      icon: "FileText",
      href: "/user/hop-dong-tai-lieu",
    },
  ],
  interestedProjects: [
    {
      id: "proj_op",
      name: "Vinhomes Ocean Park",
      slug: "vinhomes-ocean-park",
      location: "Gia Lâm, Hà Nội",
      priceText: "Giá từ: 54 tr/m²",
      statusLabel: "ĐANG QUAN TÂM",
      statusType: "interested",
      image: "/images/user/projects/ocean-park.jpg",
      href: "/du-an/vinhomes-ocean-park",
      isSaved: true,
    },
    {
      id: "proj_sc",
      name: "Vinhomes Smart City",
      slug: "vinhomes-smart-city",
      location: "Nam Từ Liêm, Hà Nội",
      priceText: "Giá từ: 56 tr/m²",
      statusLabel: "ĐANG KHẢO SÁT",
      statusType: "surveying",
      image: "/images/user/projects/smart-city.jpg",
      href: "/du-an/vinhomes-smart-city",
      isSaved: true,
    },
    {
      id: "proj_gp",
      name: "Vinhomes Grand Park",
      slug: "vinhomes-grand-park",
      location: "TP. Thủ Đức, TP. HCM",
      priceText: "Giá từ: 48 tr/m²",
      statusLabel: "ĐÃ THAM QUAN",
      statusType: "visited",
      image: "/images/user/projects/grand-park.jpg",
      href: "/du-an/vinhomes-grand-park",
      isSaved: true,
    },
  ],
  appointments: [
    {
      id: "appt_01",
      title: "Tham quan Vinhomes Ocean Park",
      date: "18",
      month: "Th05",
      time: "09:30 - 11:00",
      location: "Gia Lâm, Hà Nội",
      type: "visit",
      status: "confirmed",
    },
    {
      id: "appt_02",
      title: "Tư vấn chính sách bán hàng",
      date: "21",
      month: "Th05",
      time: "14:00 - 15:00",
      location: "Online qua Zoom",
      type: "consult",
      status: "pending",
    },
    {
      id: "appt_03",
      title: "Tham quan căn hộ mẫu",
      date: "25",
      month: "Th05",
      time: "10:00 - 11:30",
      location: "Vinhomes Smart City",
      type: "visit",
      status: "upcoming",
    },
  ],
  progressProjectName: "Vinhomes Ocean Park",
  progressSteps: [
    {
      id: "step_01",
      title: "Đặt cọc",
      statusLabel: "Hoàn thành",
      dateText: "15/04/2025",
      status: "completed",
    },
    {
      id: "step_02",
      title: "Ký HĐMB",
      statusLabel: "Đang thực hiện",
      dateText: "Dự kiến 25/05/2025",
      status: "active",
    },
    {
      id: "step_03",
      title: "Thanh toán",
      statusLabel: "Chưa đến hạn",
      dateText: "Dự kiến 25/06/2025",
      status: "pending",
    },
    {
      id: "step_04",
      title: "Nhận bàn giao",
      statusLabel: "Chưa đến hạn",
      dateText: "Dự kiến Q4/2026",
      status: "pending",
    },
  ],
  documents: [
    {
      id: "doc_01",
      title: "Hợp đồng mua bán",
      fileType: "PDF",
      fileSize: "2.4 MB",
      href: "#",
      isNew: false,
    },
    {
      id: "doc_02",
      title: "Bảng giá & CSBH",
      fileType: "PDF",
      fileSize: "1.8 MB",
      href: "#",
      isNew: true,
    },
    {
      id: "doc_03",
      title: "Chính sách bán hàng",
      fileType: "PDF",
      fileSize: "1.2 MB",
      href: "#",
      isNew: false,
    },
    {
      id: "doc_04",
      title: "Brochure dự án",
      fileType: "PDF",
      fileSize: "5.6 MB",
      href: "#",
      isNew: false,
    },
  ],
  notifications: [
    {
      id: "not_01",
      title: "Lịch hẹn tham quan đã được xác nhận",
      description: "Vinhomes Ocean Park - 18/05/2025",
      time: "10 phút trước",
      type: "appointment",
      isUnread: true,
    },
    {
      id: "not_02",
      title: "Chương trình ưu đãi mới dành cho KH",
      description: "Ưu đãi lãi suất 0% trong 18 tháng",
      time: "2 giờ trước",
      type: "promotion",
      isUnread: true,
    },
    {
      id: "not_03",
      title: "Tài liệu mới được cập nhật",
      description: "Bảng giá tháng 05/2025",
      time: "1 ngày trước",
      type: "document",
      isUnread: false,
    },
    {
      id: "not_04",
      title: "Yêu cầu tư vấn đang được xử lý",
      description: "Chuyên viên sẽ liên hệ trong 24h",
      time: "2 ngày trước",
      type: "support",
      isUnread: false,
    },
  ],
  supportContacts: [
    {
      id: "sup_hotline",
      title: "Hotline 24/7",
      value: "1900 2323 89",
      description: "Nhánh 1",
      type: "hotline",
    },
    {
      id: "sup_zalo",
      title: "Chat Zalo",
      value: "Nhắn tin ngay",
      description: "Phản hồi trong 5 phút",
      type: "zalo",
    },
    {
      id: "sup_email",
      title: "Email hỗ trợ",
      value: "cskh@vinhomes.vn",
      description: "Phản hồi trong 24h",
      type: "email",
    },
  ],
};
